name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:alpine
    steps:
      - uses: actions/checkout@v2
      - name: go-test
        run: go test -v ./... -bench=. -cover
